spring.application.name=musica

spring.datasource.url=jdbc:mysql://localhost:3306/musica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Johan123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=mi_clave_secreta_para_jwt_1234567890
jwt.expirationMs=3600000
